from enum import Enum


class EventTypes(Enum):
    PATIENT_ARRIVAL_URGENT = "PATIENT_ARRIVAL_URGENT"
    PATIENT_ARRIVAL_ORDINARY = "PATIENT_ARRIVAL_ORDINARY"
    ADMIN_WORK_COMPLETED = "ADMIN_WORK_COMPLETED"
    LAB_WORK_COMPLETE = "LAB_WORK_COMPLETE"
    MOVE_TO_OR = "MOVE_TO_OR"
    OPERATION_COMPLETE = "OPERATION_COMPLETE"
    OR_CLEAN_UP_COMPLETE = "OR_CLEAN_UP_COMPLETE"
    ICU_DEPARTURE = "ICU_DEPARTURE"
    CCU_DEPARTURE = "CCU_DEPARTURE"
    GENERAL_DEPARTURE = "GENERAL_DEPARTURE"
    EMERGENCY_DEPARTURE = "EMERGENCY_DEPARTURE"
    POWER_OUT = "POWER_OUT"
    POWER_BACK = "POWER_BACK"
